### ISSUE TITLE
Talent: Healing Way broken

### ISSUE THREAD

**Issue by pucko91** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#34]
Realm of Shadows 3.3.5 Error Report Form

Report ID: Titum007

Reporter Name: Titum

Date/Time: 170128 12:48ST

Error Severity: big

Zone/Instance: --

What type of error occurred?: The talent Healing Way doesn't stack the target with improved healing waves buff (max stack of 3) it doesn't do anything to improve that abilities healing and is broken.

What was the actual result vs. the expected result?: Actual result is nothing! expected is getting a stack on your healed target that improves Healing Wave.

Can the error be repeated? If so, what are the steps?: Make Shammy, specc it.

Link to Video Evidence: easily repeatable so not required imo

External/Related Links: http://wowwiki.wikia.com/wiki/Healing_Way

Please detail your character’s race, class, and items (optional): Orc Shaman.

**Comment by lajhar** [comment]
![image](https://cloud.githubusercontent.com/assets/20255946/22662831/abc2117e-ecaa-11e6-940c-69659b372a8d.png)  **Patch 3.2.0** (04-Aug-2009): Redesigned. Rather than providing a chance of increasing Healing Wave spells on a friendly target, this talent now innately increases the effectiveness of the shaman's Healing Wave by 8/16/25%.

Although RoS is a progressing realm and we are trying to follow the patchnotes, we are focusing mostly on the PvE and PvP content release and stuff related to them. Hundreds of spell and item modifications happened between 3.0.1 and 3.3.5, and it's impossible to retract our core and DB to blizz conditions. In addition, such changes were mostly balancing changes, it would be pointless to rework them (means once they found reasonable to modify them).
