### ISSUE TITLE
Auction house cut too big

### ISSUE THREAD

**Issue by execcc** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#52]
The cut which the auction house takes after a successful auction is too big (more than 10%), should be 5% which can be seen here: http://wowwiki.wikia.com/wiki/Formulas:Auction_House under "Fees". Alliance side if that matters.

Example mail after completed auction: http://i.imgur.com/hOrBsM9.png

**Comment by papoolee** [comment]
" In the neutral house:
Cut = 0.15 * Winning Bid "

Neutral AH = the combined Horde + Alliance AH. 
Which is what we've got on RoS right now!

**Comment by execcc** [comment]
Seems like you're right but factioned deposits and cuts would probably result in more auctions for more obscure items that otherwise gets vendored.

**Comment by dangreenberggit** [comment]
Neutral AH have a purpose, especially with faction balance issues, but making the faction AH's neutral with the consequent AH cuts is borderline gamebreaking and makes certain professions nonviable. For herbs and enchant mats it's different, but for people selling gems or leathers, for example, a few single gems or leathers can easily be 50g in AH deposits and 20g in AH cuts. 

It's not simply a matter of straight percentage, as the in-game value of items is unequal, and furthermore, you cannot simply multiply the price of AH postings to make up for the loss: you are guaranteed to lose a bunch of gold on deposits. Therefore it needs to sell, and you put it on the AH *cheaper* because you cannot afford to not make the sale. It's the same case for everyone in that profession, and so the profession bombs.

Option A) switch to factional AH formulas for deposits and cuts (the downside of this not being blizzlike flows from the lack of factional AH not being blizzlike)
Option B) make factional AH's factional (faction imbalance consequences will take their course, but arguably, blizzlike rules + faction imbalance = not very blizzlike gameplay for Allies)
Option C) Status quo (also not very blizzlike since certain professions have no affordable AH to use)

Arguably, Option A results in the most blizzlike experience. There are arguments for every option, no solution is a 100% clone of retail.

**Comment by ukidono** [comment]
"a 5% cut will be taken by the auction house (15% in neutral auction houses)"  [source](http://et.worldofwarcraft.wikia.com/wiki/Auction_House#Selling_items)

@Zerixx Below are the formulas to modify the Neutral AH code to Factioned AH
http://wowwiki.wikia.com/wiki/Formulas:Auction_House

This just feels so bad and cuts the money circulating throughtout the economy by a big margin.
![image](https://cloud.githubusercontent.com/assets/5203307/23332873/e279d030-fb91-11e6-9c1b-501a92b13d3c.png)

**Comment by Zerixx** [comment]
Until we come up with a gold sink, we're gonna keep this as it is.

**Comment by ukidono** [comment]
@Zerixx Fair enough i see your point very clearly. To not overflow the market prices it's a good strategy and thinking on your side. The "Auction house cut" will serve the server  as a gold sink.
However Deposit money discourages many people for not using the AH. Which you wouldn't want as it will lead to a dead economy.

On the Picture below you'll see a stack of Saronite bar selling at 62,50g. And the deposit for it is insanely high at 37,5g which you lose if you are unable to sell the item. that'll be 75g loss for me if i can't sell it.
In this case I'd rather sell my saronite bars to NPC at 25g a stack without risking almost 75g. This is somewhat insane.
No economy exists that you risk 40g to profit 25g.

To keep People more active in the AH, at least the deposit cost should be revised.

![image](https://cloud.githubusercontent.com/assets/5203307/23516231/ae15bc7e-ff7d-11e6-932a-f302aa33a055.png)

**Comment by Donlund** [comment]
I have to agree that despite probably acting as an effective gold sink the trading through the Auction House is a major part of the game experience. Limiting this trading affect the game heavily, especially for certain areas of the market as mentioned above. Please consider alternative gold sinks if such is already needed.

**Comment by Zerixx** [comment]
Well, we've considered many gold sinks just not decided on one.
